# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QDesktopWidget
class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(365, 186)
        Form.setWindowTitle("居中显示窗口")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # 实现窗口居中显示
        screen = QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move(int((screen.width() - size.width()) / 2),
                  int((screen.height() - size.height()) / 2))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

if __name__=='__main__':
    import sys
    app= QApplication(sys.argv) # 创建窗口程序
    main=QtWidgets.QMainWindow()
    ui=Ui_Form()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())