# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests,re
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QInputDialog, QApplication

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 272)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 20, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 80, 381, 151))
        self.label.setText("")
        self.label.setObjectName("label")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.getImage) # 绑定信号

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "设计签名"))

    def getImage(self):
        name,ok=QInputDialog.getText(main,"姓名","请输入姓名",QtWidgets.QLineEdit.Normal,"小王")
        if ok:
            name = name.replace(' ', '')  # 去掉空格
            if name == '':
                self.label.setText('请输入数据')
            else:
                starUrl = 'http://www.uustv.com/'
                data = {  # 提交数据（post方式传递）
                    'word': name,
                    'sizes': 60,
                    'fonts': 'lfc.ttf'
                }
                r = requests.post(starUrl, data=data)
                r.encoding = 'utf-8'  # 转换utf8格式
                html = r.text # 获取网页文本内容
                reg = '<div class="tu">.*?<img src="(.*?)"/></div>'
                imagePath = re.findall(reg, html)
                imgUrl = starUrl + imagePath[0]# 图片完整路径
                response = requests.get(imgUrl).content# 获取图片内容
                f = open('{}.gif'.format(name), 'wb')
                f.write(response)
                photo = QPixmap('{}.gif'.format(name))
                self.label.setPixmap(photo)  # 显示签名图片

if __name__=='__main__':
    import sys
    app=QApplication(sys.argv) # 创建窗口程序
    main=QtWidgets.QMainWindow()
    ui=Ui_Form()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())