# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNote = QtWidgets.QAction(MainWindow)
        self.actionNote.setObjectName("actionNote")
        self.actionCalc = QtWidgets.QAction(MainWindow)
        self.actionCalc.setObjectName("actionCalc")
        self.actionPaint = QtWidgets.QAction(MainWindow)
        self.actionPaint.setObjectName("actionPaint")
        self.actionIDLE = QtWidgets.QAction(MainWindow)
        self.actionIDLE.setObjectName("actionIDLE")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionNote)
        self.menu.addAction(self.actionCalc)
        self.menu.addAction(self.actionPaint)
        self.menu.addAction(self.actionIDLE)
        self.menu_2.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "常用工具"))
        self.menu_2.setTitle(_translate("MainWindow", "系统"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNote.setText(_translate("MainWindow", "Note"))
        self.actionCalc.setText(_translate("MainWindow", "Calc"))
        self.actionPaint.setText(_translate("MainWindow", "Paint"))
        self.actionIDLE.setText(_translate("MainWindow", "IDLE"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
